services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ../.env
        environment:
            - PG_HOS=db
        depends_on:
            - db
        ports:
            - "8000:8000"
    db:
        image: postgres:15
        env_file:
            - ../.env

        restart: always
        volumes:
            - ./docker/data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
